### PR TITLE
added functional test

### PR DESCRIPTION
**Pull request by tarekziade**
- Runs a local cluster with `tiup`
- Runs the python client against it

### CODE REVIEW

**Comment by tarekziade** [comment]
@andylokandy first shot at test coverage, let me know what you think. if that approach is OK, I can add more, do a cleanup etc.

`tiup` seems to be the simplest way to start a localcluster with no pain

**Comment by andylokandy** [comment]
Could you add the test to ci?

**Comment by tarekziade** [comment]
@andylokandy I am not sure why it does not trigger the GH action on `pull_request` maybe because I forked in another repo?

**Comment by tarekziade** [comment]
> Could you add the test to ci?

@andylokandy  Done -- I skipped Windows I am not sure how to start `tiup` in that environment in a robust way

**Review by andylokandy — APPROVED** [review]

**Comment by andylokandy** [comment]
Awesome! Thank you!

**Pull request merged**
